services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: bnb-backend-proxy
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - BINANCE_REST_URL=https://api.binance.com
      - BINANCE_WS_STREAMS_URL=wss://stream.binance.com:9443/ws
    networks:
      - bnb-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: bnb-frontend-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bnb-network

networks:
  bnb-network:
    driver: bridge
